CREATE TABLE [dbo].[Profesors]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Nume] NVARCHAR(50) NOT NULL, 
    [Prenume] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [Titlu] NVARCHAR(50) NOT NULL
)
