//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTISchedule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTIScheduleDBEntities : DbContext
    {
        public CTIScheduleDBEntities()
            : base("name=CTIScheduleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Activitate> Activitates { get; set; }
        public virtual DbSet<Disciplina> Disciplinas { get; set; }
        public virtual DbSet<DisciplinaProfesor> DisciplinaProfesors { get; set; }
        public virtual DbSet<Generatie> Generaties { get; set; }
        public virtual DbSet<Grupa> Grupas { get; set; }
        public virtual DbSet<Modul> Moduls { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<SubGrupa> SubGrupas { get; set; }
        public virtual DbSet<Zile> Ziles { get; set; }
        public virtual DbSet<DisciplinaActivitate> DisciplinaActivitates { get; set; }
    }
}
