//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTISchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplinaActivitate
    {
        public int Id_Disciplina { get; set; }
        public int Id_Activitate { get; set; }
        public int NrOre { get; set; }
    
        public virtual Activitate Activitate { get; set; }
        public virtual Disciplina Disciplina { get; set; }
    }
}
