//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTISchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public int Capacitate { get; set; }
        public int Activitate { get; set; }
    
        public virtual Activitate Activitate1 { get; set; }
    }
}
